BootStrapPractice/Controllers/CaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BootStrapPractice.Controllers
{
    public class CaseController : Controller
    {
        // GET: Case
        public ActionResult Index()
        {
            return View();
        }
    }
}

BootStrapPractice/Controllers/InformationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BootStrapPractice.Controllers
{
    public class InformationController : Controller
    {
        // GET: Information
        public ActionResult Index()
        {
            return View();
        }
    }
}

BootStrapPractice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    @*<meta name="viewport" content="width=device-width, initial-scale=1.0">*@
    <meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1, user-scalable=no">
    <title>@ViewBag.Title - PracticeBootStrap Useing Youtube 北風網 瓢城Web俱樂部教材 </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/Style.css" rel="stylesheet" />
    <link href="~/Content/JqueryPractice.css" rel="stylesheet" />
</head>

<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a href="#" class="navbar-brand logo"><img src="~/Image/logo.png" alt="Test" /></a>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <div class="collapse navbar-collapse" id="navbar-collapse" >
                <ul class="nav navbar-nav navbar-right">
                    <li class="active"><a href="@Url.Action("Index","Home")"><span class="glyphicon glyphicon-home"></span> 首頁</a></li>
                    <li><a href="@Url.Action("Index","Information")"><span class="glyphicon glyphicon-list"></span> 資訊</a></li>
                    <li><a href="@Url.Action("Index","Case")"><span class="glyphicon glyphicon-fire"></span> 案例</a></li>
                    <li><a href="@Url.Action("About","Home")"><span class="glyphicon glyphicon-question-sign"></span> 關於</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div>
        @RenderBody()
        <footer id="footer">
            <div class="container">
                <p>企業培訓 | 合作事宜 | 版權投訴</p>
                <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 應用程式</p>
            </div>
        </footer>
    </div>
        
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/jqueryForLayout.js"></script>
    <script src="~/Scripts/JqueryPractice.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>